CREATE TABLE IF NOT EXISTS shopify_access_tokens (
    id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    access_token TEXT NOT NULL,
    expires_at DATETIME NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
